# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/rhode/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rhode)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,d68414a8e8f4a1f805a490957c910659f183a5eb)
$(call add-radio-file-sha1-checked,radio/modem.img,f6a2aa6cde8ec05af18c5b56e18e3ca11ac730f7)
$(call add-radio-file-sha1-checked,radio/abl.img,d7abd73f3190b30dc3b05ebe5e728f6b5be8f223)
$(call add-radio-file-sha1-checked,radio/devcfg.img,843b775a007fc179fbda63214e945c9b618ee5a1)
$(call add-radio-file-sha1-checked,radio/dsp.img,4144ffeb26921b1051bc4978024a19bcadc2cc03)
$(call add-radio-file-sha1-checked,radio/fsg.img,d04cc1fb24f1a9ed9826a7790c3b4298621f30a4)
$(call add-radio-file-sha1-checked,radio/hyp.img,7f26d6bf94004a518be104b805b89e638f5ed328)
$(call add-radio-file-sha1-checked,radio/keymaster.img,53710fd13cfaa9517128171b41f18941e0480481)
$(call add-radio-file-sha1-checked,radio/logo.img,d583611a5da97c9bd5171b3f94c243dfd8b920dc)
$(call add-radio-file-sha1-checked,radio/prov.img,cf53f7648867e43c4720091b4e88919e0154f0a6)
$(call add-radio-file-sha1-checked,radio/qupfw.img,46f316ec9f88030ca132417ad55ab41c82cec49c)
$(call add-radio-file-sha1-checked,radio/rpm.img,f25dab3a26c607bac02d7cbd765c28044805461d)
$(call add-radio-file-sha1-checked,radio/storsec.img,7cacad15e5ca4f5d00436d51d95fbe8cac47d25f)
$(call add-radio-file-sha1-checked,radio/tz.img,978f22ebf16a3407ae92d986667c5d2a45fd972e)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,c78c272e1e831c8660bd67b708304382b3f914c0)
$(call add-radio-file-sha1-checked,radio/xbl.img,0930bba842c37d0f5501dfe24066f9b8f0829def)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,379a8217a6422134ec2a0e47f04de9305fe5dead)

endif
